// ./styles/ChapterScreenStyles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const ACCENT = 'rgba(243,99,22,1)';
const ACCENT_LIGHT = 'rgba(243,99,22,0.7)';
const ACCENT_SOFT = 'rgba(243,99,22,0.15)';
const ACCENT_GRADIENT = [ACCENT, 'rgba(243,99,22,0.7)', 'rgba(243,99,22,0.3)'];
const BG = '#101014';
const WHITE = '#fff';
const TEXT = '#f5f5f5';
const SUBTEXT = '#e0e0e0';
const SHADOW = 'rgba(0,0,0,0.7)';

export const styles = StyleSheet.create({
  // Main container
  container: {
    flex: 1,
    backgroundColor: BG,
    paddingBottom: 0,
  },
  // Header with accent bar
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 36,
    paddingBottom: 18,
    backgroundColor: ACCENT_SOFT,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 24,
    fontWeight: 'bold',
    color: ACCENT,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  headerButton: {
    padding: 8,
    borderRadius: 16,
    backgroundColor: ACCENT_SOFT,
    marginHorizontal: 2,
  },
  // Balance/info bar
  balanceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: ACCENT_SOFT,
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 18,
    padding: 10,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  balanceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 6,
  },
  balanceIcon: {
    marginRight: 6,
  },
  balanceText: {
    color: ACCENT,
    fontWeight: 'bold',
    fontSize: 15,
    letterSpacing: 0.2,
  },
  // Chapter content
  contentContainer: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 24,
  },
  paragraph: {
    color: TEXT,
    fontSize: 20,
    lineHeight: 32,
    marginBottom: 18,
    letterSpacing: 0.1,
    textAlign: 'left',
    backgroundColor: 'rgba(255,255,255,0.01)',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  // Navigation bar
  navigation: {
    marginTop: 18,
    marginBottom: 8,
    paddingHorizontal: 0,
    alignItems: 'center',
  },
  navRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    backgroundColor: ACCENT_SOFT,
    borderRadius: 16,
    padding: 8,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ACCENT,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 18,
    marginHorizontal: 4,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 3,
    minWidth: 90,
    justifyContent: 'center',
  },
  navButtonText: {
    color: WHITE,
    fontWeight: 'bold',
    fontSize: 16,
    marginHorizontal: 4,
    letterSpacing: 0.2,
  },
  navPlaceholder: {
    flex: 1,
    minWidth: 90,
  },
  // Feedback messages
  messageContainer: {
    marginHorizontal: 18,
    marginTop: 12,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  successMessage: {
    backgroundColor: 'rgba(243,99,22,0.18)',
    borderColor: ACCENT,
    borderWidth: 1,
  },
  errorMessage: {
    backgroundColor: 'rgba(255,0,0,0.13)',
    borderColor: 'rgba(255,0,0,0.4)',
    borderWidth: 1,
  },
  warningMessage: {
    backgroundColor: 'rgba(243,99,22,0.09)',
    borderColor: ACCENT_LIGHT,
    borderWidth: 1,
  },
  messageText: {
    color: TEXT,
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  // Locked/paid overlays
  lockedContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16,16,20,0.97)',
    padding: 24,
    borderRadius: 24,
    margin: 18,
    shadowColor: SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 8,
  },
  lockIcon: {
    marginBottom: 18,
  },
  lockedMessage: {
    color: ACCENT,
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  lockedSubMessage: {
    color: SUBTEXT,
    fontSize: 16,
    marginBottom: 18,
    textAlign: 'center',
  },
  // Payment grid/buttons
  paymentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 10,
    gap: 10,
  },
  paymentButton: {
    backgroundColor: ACCENT,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 18,
    margin: 6,
    minWidth: 120,
    alignItems: 'center',
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  paymentButtonText: {
    color: WHITE,
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 2,
  },
  paymentPrice: {
    color: ACCENT_LIGHT,
    fontSize: 13,
    fontWeight: '600',
  },
  fullChaptersButton: {
    backgroundColor: 'rgba(243,99,22,0.85)',
  },
  threeChaptersButton: {
    backgroundColor: 'rgba(243,99,22,0.65)',
  },
  disabledButton: {
    backgroundColor: 'rgba(243,99,22,0.25)',
    opacity: 0.6,
  },
  // Action buttons (e.g. Read with SMP)
  actionButtonsContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 18,
    gap: 10,
  },
  smpButton: {
    backgroundColor: ACCENT,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 28,
    marginBottom: 10,
    alignItems: 'center',
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  smpButtonText: {
    color: WHITE,
    fontWeight: 'bold',
    fontSize: 17,
    letterSpacing: 0.2,
  },
  getSmpButton: {
    backgroundColor: ACCENT_SOFT,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 4,
  },
  getSmpButtonText: {
    color: ACCENT,
    fontWeight: 'bold',
    fontSize: 15,
  },
  // Reading options (after unlock)
  readingOptions: {
    backgroundColor: ACCENT_SOFT,
    borderRadius: 12,
    padding: 10,
    marginBottom: 12,
    alignItems: 'center',
  },
  readingModeText: {
    color: ACCENT,
    fontWeight: 'bold',
    fontSize: 15,
  },
  // Loading
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BG,
  },
  loadingText: {
    color: ACCENT,
    fontSize: 18,
    marginTop: 18,
    fontWeight: 'bold',
  },
  // Error
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BG,
    padding: 24,
  },
  errorTitle: {
    color: 'rgba(255,0,0,0.8)',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    color: TEXT,
    borderRadius: 10,
    padding: 12,
    marginVertical: 8,
    fontSize: 16,
    width: width * 0.8,
    alignSelf: 'center',
  },
  actionButton: {
    backgroundColor: ACCENT,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 28,
    marginVertical: 10,
    alignItems: 'center',
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  actionButtonText: {
    color: WHITE,
    fontWeight: 'bold',
    fontSize: 17,
  },
  secondaryButton: {
    backgroundColor: ACCENT_SOFT,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginVertical: 4,
  },
  secondaryButtonText: {
    color: ACCENT,
    fontWeight: 'bold',
    fontSize: 15,
  },
});