// ./styles/ChapterScreenStyles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A2E',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A1A2E',
  },
  loadingText: {
    color: '#ffffff',
    fontSize: 16,
    marginTop: 10,
    fontFamily: 'Inter-Regular',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#1A1A2E',
  },
  errorTitle: {
    color: '#FF5252',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
  },
  input: {
    width: width * 0.9,
    backgroundColor: '#2A2A4A',
    borderRadius: 12,
    padding: 15,
    color: '#ffffff',
    fontSize: 16,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: '#3A3A5A',
    fontFamily: 'Inter-Regular',
  },
  actionButton: {
    backgroundColor: '#E67E22',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 30,
    marginVertical: 10,
    width: width * 0.9,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  actionButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    marginVertical: 10,
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    marginLeft: 8,
    fontFamily: 'Inter-Regular',
  },
  buttonIcon: {
    marginRight: 8,
  },
  balanceContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(42, 42, 74, 0.9)',
    borderRadius: 12,
    padding: 10,
    flexDirection: 'column',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  balanceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  balanceIcon: {
    marginRight: 8,
  },
  balanceText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: 'Inter-Regular',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(26, 26, 46, 0.95)',
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A5A',
  },
  headerButton: {
    padding: 10,
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Inter-Bold',
  },
  messageContainer: {
    padding: 15,
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
  },
  successMessage: {
    backgroundColor: 'rgba(230, 126, 34, 0.2)',
    borderWidth: 1,
    borderColor: '#E67E22',
  },
  errorMessage: {
    backgroundColor: 'rgba(255, 82, 82, 0.2)',
    borderWidth: 1,
    borderColor: '#FF5252',
  },
  messageText: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: 'Inter-Regular',
  },
  lockedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  lockIcon: {
    marginBottom: 20,
  },
  lockedMessage: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Inter-SemiBold',
  },
  lockedSubMessage: {
    color: '#E67E22',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 20,
    fontFamily: 'Inter-SemiBold',
  },
  paymentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: width * 0.9,
  },
  paymentButton: {
    width: width * 0.42,
    borderRadius: 12,
    padding: 15,
    marginVertical: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  threeChaptersButton: {
    backgroundColor: '#E67E22',
  },
  fullChaptersButton: {
    backgroundColor: '#D35400',
  },
  disabledButton: {
    backgroundColor: '#3A3A5A',
    opacity: 0.6,
  },
  paymentButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 5,
    fontFamily: 'Inter-SemiBold',
    textAlign: 'center',
  },
  paymentPrice: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'Inter-Regular',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  readingOptions: {
    alignItems: 'center',
    marginVertical: 20,
  },
  smpButton: {
    backgroundColor: '#E67E22',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 30,
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.9,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  smpButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'Inter-SemiBold',
  },
  readingModeText: {
    color: '#888',
    fontSize: 14,
    marginTop: 10,
    fontFamily: 'Inter-Regular',
  },
  paragraph: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 15,
    fontFamily: 'Inter-Regular',
  },
  navigation: {
    paddingVertical: 20,
  },
  navRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A4A',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flex: 1,
    marginHorizontal: 5,
    justifyContent: 'center',
  },
  navButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
  },
  navPlaceholder: {
    flex: 1,
    marginHorizontal: 5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalContent: {
    backgroundColor: '#2A2A4A',
    borderRadius: 16,
    padding: 20,
    width: width * 0.9,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 10,
  },
  modalTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 15,
    fontFamily: 'Inter-Bold',
  },
  modalSubtitle: {
    color: '#ffffff',
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Inter-Regular',
  },
  transactionDetails: {
    width: '100%',
    marginBottom: 20,
  },
  detailText: {
    color: '#ffffff',
    fontSize: 14,
    marginVertical: 5,
    fontFamily: 'Inter-Regular',
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalConfirmButton: {
    backgroundColor: '#E67E22',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  modalCancelButton: {
    backgroundColor: '#FF5252',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
  },
  modalNote: {
    color: '#888',
    fontSize: 12,
    marginTop: 10,
    textAlign: 'center',
    fontFamily: 'Inter-Regular',
  },
  passwordModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)', // Semi-transparent to see story
  },
  keyboardAvoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  passwordModalContent: {
    backgroundColor: '#2A2A4A',
    borderRadius: 16,
    padding: 15,
    width: width * 0.75, // Compact width
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  passwordModalTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    fontFamily: 'Inter-Bold',
  },
  passwordInput: {
    width: '100%',
    backgroundColor: '#3A3A5A',
    borderRadius: 10,
    padding: 12,
    color: '#ffffff',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#4A4A6A',
    fontFamily: 'Inter-Regular',
  },
  inputError: {
    borderColor: '#FF5252',
  },
  passwordErrorText: {
    color: '#FF5252',
    fontSize: 12,
    marginTop: 5,
    marginBottom: 10,
    fontFamily: 'Inter-Regular',
  },
  passwordModalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
  },
  passwordModalConfirmButton: {
    backgroundColor: '#E67E22',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  passwordModalCancelButton: {
    backgroundColor: '#FF5252',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  passwordModalButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
  },
});