import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F28C38',
    paddingVertical: 8,
    paddingHorizontal: 12,
    paddingTop: 36,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  logo: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginRight: 8,
  },
  menuButton: {
    padding: 8,
    marginRight: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginRight: 8,
  },
  chatArea: {
    flex: 1,
  },
  sidebar: {
    width: width * 0.75,
    backgroundColor: '#fff',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  sidebarContent: {
    flex: 1,
    padding: 12,
  },
  searchInput: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f7f9fc',
    fontSize: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e8ecef',
  },
  chatList: {
    paddingBottom: 16,
  },
  chatItem: {
    padding: 8,
    borderRadius: 8,
    marginVertical: 2,
  },
  activeChatItem: {
    backgroundColor: '#fef5eb',
  },
  chatItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  chatAvatarPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e8ecef',
  },
  chatItemText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    flex: 1,
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
    paddingVertical: 6,
    marginBottom: 4,
  },
  messageList: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexGrow: 1,
  },
  messageContainer: {
    marginVertical: 2,
    maxWidth: '85%',
  },
  ownMessage: {
    alignSelf: 'flex-end',
  },
  otherMessage: {
    alignSelf: 'flex-start',
  },
  messageBubble: {
    backgroundColor: '#fef5eb',
    borderRadius: 12,
    padding: 6,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    minWidth: 100,
    maxWidth: width * 0.75,
  },
  ownMessageBubble: {
    backgroundColor: '#f4c197',
  },
  messageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 6,
  },
  avatarPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e8ecef',
    marginRight: 6,
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nameContainer: {
    flexShrink: 1,
    maxWidth: '100%',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#F28C38',
    flexShrink: 1,
  },
  badge: {
    marginLeft: 4,
  },
  badgeImage: {
    width: 10,
    height: 10,
    marginLeft: 4,
  },
  messageStatus: {
    fontSize: 8,
    color: '#666',
    marginRight: 4,
  },
  messageText: {
    fontSize: 14,
    color: '#333',
    lineHeight: 18,
    flexShrink: 1,
  },
  media: {
    width: 160,
    height: 100,
    borderRadius: 8,
    marginTop: 4,
  },
  replyPreview: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 6,
    padding: 4,
    marginBottom: 4,
    borderLeftWidth: 2,
    borderLeftColor: '#F28C38',
  },
  replyName: {
    fontSize: 11,
    fontWeight: '600',
    color: '#F28C38',
    marginBottom: 1,
  },
  replyContent: {
    fontSize: 11,
    color: '#555',
  },
  replyButton: {
    padding: 4,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f7f9fc',
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: '#e8ecef',
  },
  replyText: {
    flex: 1,
    fontSize: 12,
    color: '#333',
  },
  replyName: {
    fontWeight: '600',
    color: '#F28C38',
  },
  cancelReply: {
    padding: 4,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: '#e8ecef',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  input: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#f7f9fc',
    fontSize: 14,
    maxHeight: 80,
    marginHorizontal: 4,
  },
  inputButton: {
    padding: 8,
  },
  sendButton: {
    padding: 8,
  },
  gifModal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  gifContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    padding: 12,
    maxHeight: height * 0.4,
  },
  gifHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  gifInput: {
    flex: 1,
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f7f9fc',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#e8ecef',
  },
  closeButton: {
    padding: 8,
  },
  gifGrid: {
    paddingBottom: 8,
  },
  gifItem: {
    flex: 1,
    margin: 4,
  },
  gifImage: {
    width: '100%',
    height: 80,
    borderRadius: 6,
  },
  noGifs: {
    textAlign: 'center',
    color: '#666',
    fontSize: 13,
    marginVertical: 8,
  },
  typingIndicator: {
    padding: 6,
    backgroundColor: '#f7f9fc',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  typingText: {
    fontSize: 11,
    color: '#666',
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#EF5350',
    padding: 8,
    marginHorizontal: 12,
    marginVertical: 4,
    borderRadius: 8,
  },
  errorText: {
    color: '#fff',
    fontSize: 13,
    flex: 1,
  },
  loadingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
  },
  loadingText: {
    color: '#666',
    fontSize: 13,
    marginLeft: 8,
  },
  emojiPicker: {
    height: height * 0.35,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e8ecef',
    paddingBottom: 8,
  },
});