import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F28C38',
    paddingVertical: 8,
    paddingHorizontal: 12,
    paddingTop: 36,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  logo: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginRight: 8,
  },
  menuButton: {
    padding: 8,
    marginRight: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginRight: 8,
  },
  chatArea: {
    flex: 1,
  },
  sidebar: {
    width: width * 0.75,
    backgroundColor: '#fff',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
    elevation: 8,
    shadowColor: '#F28C38',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    overflow: 'hidden',
  },
  sidebarOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: width,
    height: height,
    backgroundColor: 'rgba(0,0,0,0.18)',
    zIndex: 15,
  },
  sidebarContent: {
    flex: 1,
    padding: 12,
  },
  searchInput: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f7f9fc',
    fontSize: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e8ecef',
  },
  chatList: {
    paddingBottom: 16,
  },
  chatItem: {
    padding: 10,
    borderRadius: 12,
    marginVertical: 4,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  activeChatItem: {
    backgroundColor: '#fef5eb',
    borderLeftWidth: 4,
    borderLeftColor: '#F28C38',
  },
  chatItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#F28C38',
  },
  chatAvatarPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e8ecef',
    marginRight: 10,
  },
  chatItemText: {
    fontSize: 15,
    color: '#333',
    fontWeight: '600',
    flex: 1,
  },
  divider: {
    height: '100%',
    width: 1.5,
    backgroundColor: '#f4c197',
    position: 'absolute',
    left: width * 0.75 - 1.5,
    top: 0,
    zIndex: 21,
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
    paddingVertical: 6,
    marginBottom: 4,
  },
  messageList: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexGrow: 1,
  },
  messageContainer: {
    marginVertical: 2,
    maxWidth: '85%',
  },
  ownMessage: {
    alignSelf: 'flex-end',
  },
  otherMessage: {
    alignSelf: 'flex-start',
  },
  messageBubble: {
    backgroundColor: '#f7f7fa',
    borderRadius: 22,
    padding: 12,
    minWidth: 100,
    maxWidth: width * 0.75,
    marginBottom: 2,
    borderBottomLeftRadius: 6,
  },
  ownMessageBubble: {
    backgroundColor: 'rgba(242, 140, 56, 0.49)',
    borderRadius: 22,
    borderBottomRightRadius: 6,
    borderWidth: 1.5,
    borderColor: '#fbbf24',
  },
  selectedMessage: {
    borderWidth: 2,
    borderColor: '#F28C38',
    backgroundColor: 'rgba(242,140,56,0.08)',
    borderRadius: 20,
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  selectionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F28C38',
    paddingTop: 36,
    paddingBottom: 10,
    paddingHorizontal: 16,
    elevation: 6,
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    zIndex: 30,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    minHeight: 60,
    position: 'relative',
  },
  selectionBarCancel: {
    marginRight: 16,
    padding: 6,
  },
  selectionBarText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
    flex: 1,
  },
  selectionBarEdit: {
    marginRight: 16,
    padding: 6,
  },
  selectionBarDelete: {
    padding: 6,
  },
  messageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 6,
  },
  avatarPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e8ecef',
    marginRight: 6,
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nameContainer: {
    flexShrink: 1,
    maxWidth: '100%',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#F28C38',
    flexShrink: 1,
  },
  badge: {
    marginLeft: 4,
  },
  badgeImage: {
    width: 10,
    height: 10,
    marginLeft: 4,
  },
  messageStatus: {
    fontSize: 8,
    color: '#666',
    marginRight: 4,
  },
  messageText: {
    fontSize: 14,
    color: '#333',
    lineHeight: 18,
    flexShrink: 1,
  },
  media: {
    width: 160,
    height: 100,
    borderRadius: 8,
    marginTop: 4,
  },
  replyPreview: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 6,
    padding: 4,
    marginBottom: 4,
    borderLeftWidth: 2,
    borderLeftColor: '#F28C38',
  },
  replyName: {
    fontSize: 11,
    fontWeight: '600',
    color: '#F28C38',
    marginBottom: 1,
  },
  replyContent: {
    fontSize: 11,
    color: '#555',
  },
  replyButton: {
    padding: 4,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f7f9fc',
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: '#e8ecef',
  },
  replyText: {
    flex: 1,
    fontSize: 12,
    color: '#333',
  },
  replyName: {
    fontWeight: '600',
    color: '#F28C38',
  },
  cancelReply: {
    padding: 4,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#e8ecef',
    elevation: 4,
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    marginHorizontal: 6,
    marginBottom: 8,
  },
  input: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: '#f7f9fc',
    fontSize: 15,
    maxHeight: 100,
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: '#f4c197',
  },
  inputButton: {
    padding: 10,
    borderRadius: 24,
    backgroundColor: '#fff7ed',
    marginLeft: 4,
    elevation: 1,
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  sendButton: {
    padding: 10,
    borderRadius: 24,
    backgroundColor: '#F28C38',
    marginLeft: 4,
    elevation: 2,
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
  },
  checkmarkOverlay: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: '#F28C38',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#F28C38',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  gifModal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  gifContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    padding: 12,
    maxHeight: height * 0.4,
  },
  gifHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  gifInput: {
    flex: 1,
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f7f9fc',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#e8ecef',
  },
  closeButton: {
    padding: 8,
  },
  gifGrid: {
    paddingBottom: 8,
  },
  gifItem: {
    flex: 1,
    margin: 4,
  },
  gifImage: {
    width: '100%',
    height: 80,
    borderRadius: 6,
  },
  noGifs: {
    textAlign: 'center',
    color: '#666',
    fontSize: 13,
    marginVertical: 8,
  },
  typingIndicator: {
    padding: 6,
    backgroundColor: '#f7f9fc',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  typingText: {
    fontSize: 11,
    color: '#666',
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#EF5350',
    padding: 8,
    marginHorizontal: 12,
    marginVertical: 4,
    borderRadius: 8,
  },
  errorText: {
    color: '#fff',
    fontSize: 13,
    flex: 1,
  },
  loadingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
  },
  loadingText: {
    color: '#666',
    fontSize: 13,
    marginLeft: 8,
  },
  emojiPicker: {
    height: height * 0.35,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e8ecef',
    paddingBottom: 8,
  },
  scrollToBottomButton: {
    position: 'absolute',
    right: 20,
    bottom: 80,
    backgroundColor: '#F28C38',
    borderRadius: 24,
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    zIndex: 20,
  },
  scrollToBottomIcon: {
    color: '#fff',
    fontSize: 24,
  },
  editModal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    alignItems: 'stretch',
  },
  editInput: {
    borderWidth: 1,
    borderColor: '#F28C38',
    borderRadius: 8,
    padding: 10,
    fontSize: 15,
    marginBottom: 16,
    backgroundColor: '#f7f9fc',
    color: '#333',
  },
  editModalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  editModalButton: {
    marginRight: 16,
  },
  editModalCancel: {
    color: '#EF5350',
    fontWeight: 'bold',
    fontSize: 15,
  },
  editModalSave: {
    color: '#F28C38',
    fontWeight: 'bold',
    fontSize: 15,
  },
});