// ./styles/CommentSectionStyles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  commentSection: {
    marginVertical: 16,
  },
  commentSectionContainer: {
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: {
    color: '#D94F04',
    fontSize: 24,
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  errorMessage: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ff5555',
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  errorMessageText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    flex: 1,
  },
  clearErrorButton: {
    padding: 8,
  },
  connectPrompt: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(217, 79, 4, 0.2)',
  },
  connectPromptText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    marginBottom: 12,
    textAlign: 'center',
  },
  connectButton: {
    width: '100%',
    alignItems: 'center',
  },
  inputContainer: {
    marginBottom: 16,
  },
  textarea: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    padding: 12,
    borderRadius: 10,
    minHeight: 80,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#D94F04',
  },
  textareaDisabled: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    opacity: 0.5,
  },
  inputFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  charCounter: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    opacity: 0.7,
  },
  postButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D94F04',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    shadowColor: '#D94F04',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  postButtonDisabled: {
    backgroundColor: 'rgba(217, 79, 4, 0.3)',
    opacity: 0.5,
  },
  postButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    marginLeft: 8,
  },
  commentsContainer: {
    paddingBottom: 16,
  },
  comment: {
    marginBottom: 12,
  },
  commentCard: {
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  commentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  commentUsername: {
    color: '#D94F04',
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
  },
  commentTimestamp: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
    opacity: 0.7,
  },
  commentContent: {
    marginBottom: 8,
  },
  commentText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    lineHeight: 20,
  },
  commentActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    marginRight: 12,
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    marginLeft: 4,
  },
  replyInputContainer: {
    marginTop: 12,
    marginLeft: 16,
    borderLeftWidth: 2,
    borderLeftColor: '#D94F04',
    paddingLeft: 12,
  },
  replyInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    padding: 10,
    borderRadius: 8,
    minHeight: 60,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#D94F04',
  },
  replyActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  replyButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cancelReplyButton: {
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    marginRight: 8,
  },
  postReplyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D94F04',
    padding: 8,
    borderRadius: 8,
    shadowColor: '#D94F04',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  postReplyButtonDisabled: {
    backgroundColor: 'rgba(217, 79, 4, 0.3)',
    opacity: 0.5,
  },
  replies: {
    marginLeft: 16,
    marginTop: 8,
  },
  repliesContainer: {
    paddingBottom: 8,
  },
  noComments: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginVertical: 16,
    opacity: 0.7,
  },
});