import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  mainButtonContainer: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 100,
  },
  connectButton: {
    backgroundColor: '#1A1A2E',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E67E22',
    shadowColor: '#E67E22',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    minWidth: 160,
  },
  connectedButton: {
    backgroundColor: '#2A2A4A',
  },
  connectButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  buttonIcon: {
    color: '#ffffff',
    marginRight: 8,
  },
  modal: {
    margin: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1A1A2E',
    borderRadius: 24,
    padding: 32,
    width: width * 0.9,
    maxWidth: 400,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(230, 126, 34, 0.3)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  modalTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  modalText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 16,
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 24,
  },
  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButton: {
    backgroundColor: '#E67E22',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  actionButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  secondaryButton: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#2A2A4A',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
  },
  closeButton: {
    position: 'absolute',
    right: 0,
    padding: 8,
  },
  closeIcon: {
    color: '#ffffff',
  },
  input: {
    width: '100%',
    backgroundColor: '#2A2A4A',
    borderRadius: 12,
    padding: 16,
    color: '#ffffff',
    fontSize: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  inputActive: {
    borderColor: '#E67E22',
  },
  errorText: {
    color: '#FF5252',
    fontSize: 14,
    marginBottom: 16,
    textAlign: 'center',
  },
  disabledButton: {
    opacity: 0.6,
  },
  // From ConnectButton.js (first provided aesthetic)
  importButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#28a745',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '80%',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  walletInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  walletText: {
    fontSize: 16,
    color: '#333',
  },
  disconnectButton: {
    marginLeft: 10,
    backgroundColor: '#ff3b30',
    padding: 8,
    borderRadius: 5,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: '#ffffff',
    marginLeft: 8,
    fontSize: 16,
    fontFamily: 'Inter-Regular',
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    marginLeft: 10,
  },
  successMessage: {
    marginTop: 10,
    fontSize: 16,
    color: '#28a745',
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 20,
  },
  walletAddress: {
    backgroundColor: '#2A2A4A',
    padding: 20,
    borderRadius: 16,
    marginBottom: 24,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    minHeight: 56,
  },
  walletAddressText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: 'Inter-Regular',
  },
  copyIcon: {
    color: '#E67E22',
  },
  successIcon: {
    color: '#4CAF50',
    marginRight: 8,
  },
  warningContainer: {
    backgroundColor: 'rgba(230, 126, 34, 0.1)',
    padding: 20,
    borderRadius: 16,
    marginBottom: 24,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  warningIcon: {
    color: '#E67E22',
    marginRight: 12,
    marginTop: 2,
  },
  warningText: {
    color: '#E67E22',
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
    fontFamily: 'Inter-Regular',
  },

  // From styles.js (second provided aesthetic, prefixed with GradientStyle)
  containerGradientStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    pointerEvents: 'auto',
  },
  connectButtonContainerGradientStyle: {
    borderRadius: 16,
    shadowColor: '#FF5733',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  connectButtonGradientStyle: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 87, 51, 0.3)',
    overflow: 'hidden',
    pointerEvents: 'auto',
  },
  connectButtonGradientOverlayStyle: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  connectButtonTextGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  walletInfoContainerGradientStyle: {
    position: 'relative',
    alignItems: 'center',
  },
  walletInfoGradientStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1e1e1e',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FF5733',
    shadowColor: '#FF5733',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    pointerEvents: 'auto',
  },
  walletTextGradientStyle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginRight: 8,
  },
  dropdownIconGradientStyle: {
    marginLeft: 4,
  },
  dropdownGradientStyle: {
    position: 'absolute',
    top: 60,
    right: 0,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 8,
    width: 180,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
    borderWidth: 1,
    borderColor: 'rgba(255, 87, 51, 0.3)',
  },
  dropdownItemGradientStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 4,
    backgroundColor: 'rgba(255, 87, 51, 0.1)',
  },
  dropdownItemTextGradientStyle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  loadingContainerGradientStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1e1e1e',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FF5733',
  },
  loadingTextGradientStyle: {
    color: '#ffffff',
    marginLeft: 12,
    fontSize: 16,
    fontWeight: '600',
  },
  errorContainerGradientStyle: {
    alignItems: 'center',
    backgroundColor: '#ff4444',
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  errorTextGradientStyle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
    textAlign: 'center',
  },
  retryButtonGradientStyle: {
    flexDirection: 'row',
    backgroundColor: '#F36316',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  retryButtonTextGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  successMessageGradientStyle: {
    color: '#00ff00',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  modalOverlayGradientStyle: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    pointerEvents: 'auto',
  },
  popupGradientStyle: {
    backgroundColor: '#1e1e1e',
    padding: 24,
    borderRadius: 16,
    width: '85%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF5733',
    shadowColor: '#FF5733',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  popupTitleGradientStyle: {
    color: '#FF5733',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  securityNoteGradientStyle: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 16,
    textAlign: 'center',
    lineHeight: 20,
  },
  linkGradientStyle: {
    color: '#FF5733',
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
  popupOptionsGradientStyle: {
    width: '100%',
    alignItems: 'center',
  },
  popupEmbeddedButtonGradientStyle: {
    flexDirection: 'row',
    backgroundColor: '#F36316',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
    width: '100%',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    pointerEvents: 'auto',
  },
  popupButtonTextGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  cancelButtonGradientStyle: {
    padding: 12,
    pointerEvents: 'auto',
  },
  cancelButtonText_gradientStyle: {
    color: '#888',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  closeButtonGradientStyle: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 8,
    pointerEvents: 'auto',
  },
  embeddedFormGradientStyle: {
    backgroundColor: '#1e1e1e',
    padding: 24,
    borderRadius: 16,
    width: '85%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF5733',
    shadowColor: '#FF5733',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  formTitleGradientStyle: {
    color: '#FF5733',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  inputGradientStyle: {
    backgroundColor: '#2a2a2a',
    color: '#ffffff',
    width: '100%',
    padding: 14,
    borderRadius: 12,
    marginBottom: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 87, 51, 0.3)',
    pointerEvents: 'auto',
  },
  submitButtonGradientStyle: {
    flexDirection: 'row',
    backgroundColor: '#F36316',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    pointerEvents: 'auto',
  },
  submitButtonTextGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  privateKeyBoxGradientStyle: {
    backgroundColor: '#1e1e1e',
    padding: 24,
    borderRadius: 16,
    width: '85%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF5733',
    shadowColor: '#FF5733',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  privateKeyTextGradientStyle: {
    backgroundColor: '#2a2a2a',
    color: '#ffffff',
    width: '100%',
    padding: 14,
    borderRadius: 12,
    marginBottom: 16,
    fontSize: 14,
    height: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: 'rgba(255, 87, 51, 0.3)',
    pointerEvents: 'none',
  },
  labelGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    width: '100%',
    textAlign: 'left',
  },
  copyButtonGradientStyle: {
    flexDirection: 'row',
    backgroundColor: '#F36316',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    pointerEvents: 'auto',
  },
  copyButtonTextGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  referralPromptGradientStyle: {
    backgroundColor: '#1e1e1e',
    padding: 24,
    borderRadius: 16,
    width: '85%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF5733',
    shadowColor: '#FF5733',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  promptTitleGradientStyle: {
    color: '#FF5733',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  promptMessageGradientStyle: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 20,
  },
  promptButtonsGradientStyle: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  updateButtonGradientStyle: {
    flexDirection: 'row',
    backgroundColor: '#F36316',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    pointerEvents: 'auto',
  },
  updateButtonTextGradientStyle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  laterButtonGradientStyle: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    flex: 1,
    marginLeft: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#888',
    pointerEvents: 'auto',
  },
  laterButtonTextGradientStyle: {
    color: '#888',
    fontSize: 16,
    fontWeight: '600',
  },
});