import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  navbar: {
    paddingVertical: 15,
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 1000,
    borderBottomWidth: 2,
  },
  navContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: width < 360 ? 10 : 20,
  },
  logoLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: width < 360 ? 50 : 60,
    height: width < 360 ? 50 : 60,
    borderRadius: width < 360 ? 25 : 30,
    borderWidth: 3,
  },
  logoText: {
    fontSize: width < 360 ? 16 : 18,
    fontWeight: 'bold',
    marginLeft: 15,
  },
  menuToggle: {
    padding: 10,
  },
  navLinks: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 5,
  },
  navLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    marginBottom: 12,
  },
  navLinkText: {
    fontSize: 16,
    color: '#fff',
    marginLeft: 10,
    fontWeight: '600',
  },
  main: {
    padding: width < 360 ? 20 : 30,
    paddingTop: 80,
    alignItems: 'center',
    minHeight: height,
  },
  profileSection: {
    backgroundColor: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 20,
    padding: width < 360 ? 20 : 30,
    width: '100%',
    maxWidth: 600,
    borderWidth: 2,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 5,
  },
  title: {
    fontSize: width < 360 ? 24 : 28,
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: 'bold',
  },
  balanceCard: {
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
  },
  balanceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  balanceText: {
    fontSize: 16,
    color: '#fff',
    marginLeft: 12,
    fontWeight: '500',
  },
  connectWrapper: {
    alignItems: 'center',
    marginBottom: 20,
  },
  connectText: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 15,
    textAlign: 'center',
  },
  walletText: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 20,
    textAlign: 'center',
  },
  form: {
    flexDirection: 'column',
    gap: 20,
  },
  inputGroup: {
    flexDirection: 'column',
    gap: 10,
  },
  inputLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    fontSize: 16,
    fontWeight: '600',
  },
  input: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    color: '#fff',
    fontSize: 16,
    minHeight: 48, // Touch-friendly height
  },
  textarea: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    color: '#fff',
    fontSize: 16,
    minHeight: 100,
  },
  inputWithButton: {
    flexDirection: width < 360 ? 'column' : 'row',
    alignItems: width < 360 ? 'stretch' : 'center',
    gap: width < 360 ? 10 : 15,
  },
  verifyButton: {
    padding: 12,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    minWidth: width < 360 ? '100%' : 120,
  },
  buttonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
    marginLeft: 8,
  },
  verifiedText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '500',
  },
  imageGroup: {
    flexDirection: 'column',
    gap: 15,
    alignItems: 'center',
  },
  imageLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 48,
    minWidth: 150,
  },
  previewImage: {
    width: '100%',
    height: width < 360 ? 150 : 200,
    borderRadius: 15,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 5,
  },
  alertInfo: {
    padding: 12,
    borderRadius: 12,
    marginVertical: 10,
    alignItems: 'center',
  },
  alertError: {
    backgroundColor: 'rgba(220, 53, 69, 0.95)',
    padding: 15,
    borderRadius: 12,
    marginVertical: 15,
    alignItems: 'center',
  },
  alertSuccess: {
    backgroundColor: 'rgba(40, 167, 69, 0.95)',
    padding: 15,
    borderRadius: 12,
    marginVertical: 15,
    alignItems: 'center',
  },
  alertText: {
    fontSize: 14,
    color: '#fff',
    textAlign: 'center',
    fontWeight: '500',
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 30,
    gap: 10,
    minHeight: 48,
  },
  modal: {
    justifyContent: 'center',
    margin: 20,
  },
  modalContent: {
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
  },
  modalClose: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  modalText: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'center',
    fontWeight: '500',
  },
});