import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    minHeight: '100%',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0d1b2a',
  },
  header: {
    backgroundColor: 'rgba(13, 27, 42, 0.95)',
    paddingVertical: 15,
    paddingHorizontal: 25,
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 1000,
    shadowColor: '#ff6200',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 5,
  },
  nav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    maxWidth: 1200,
    marginHorizontal: 'auto',
  },
  logoLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: width <= 480 ? 35 : width <= 768 ? 40 : 45,
    height: width <= 480 ? 35 : width <= 768 ? 40 : 45,
    borderRadius: 22.5,
    borderWidth: 2,
    borderColor: '#ff6200',
  },
  logoText: {
    fontSize: width <= 480 ? 20 : width <= 768 ? 22 : 26,
    fontWeight: '700',
    color: '#ff6200',
    marginLeft: 12,
  },
  menuToggle: {
    width: width <= 480 ? 35 : 40,
    height: width <= 480 ? 35 : 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIcon: {
    width: width <= 480 ? 20 : 25,
    height: 3,
    position: 'absolute',
  },
  menuIconLine: {
    position: 'absolute',
    width: width <= 480 ? 20 : 25,
    height: 3,
    backgroundColor: '#ff6200',
  },
  menuIconBefore: {
    top: width <= 480 ? -6 : -8,
  },
  menuIconAfter: {
    bottom: width <= 480 ? -6 : -8,
  },
  navLinks: {
    flexDirection: width > 768 ? 'row' : 'column',
    alignItems: 'center',
    backgroundColor: width <= 768 ? 'rgba(13, 27, 42, 0.98)' : 'transparent',
    position: width <= 768 ? 'absolute' : 'relative',
    top: width <= 768 ? 60 : 0,
    left: 0,
    right: 0,
    paddingVertical: width <= 768 ? 20 : 0,
    shadowColor: width <= 768 ? '#ff6200' : 'transparent',
    shadowOffset: width <= 768 ? { width: 0, height: 4 } : { width: 0, height: 0 },
    shadowOpacity: width <= 768 ? 0.2 : 0,
    shadowRadius: width <= 768 ? 15 : 0,
    elevation: width <= 768 ? 5 : 0,
    zIndex: 999,
  },
  navLink: {
    paddingVertical: width <= 768 ? 12 : 8,
    paddingHorizontal: width <= 768 ? 20 : 16,
    borderBottomWidth: width <= 768 ? 1 : 0,
    borderBottomColor: width <= 768 ? 'rgba(255, 98, 0, 0.1)' : 'transparent',
    width: width <= 768 ? '100%' : 'auto',
    alignItems: 'center',
  },
  navLinkText: {
    color: '#ffffff',
    fontSize: width <= 768 ? 18 : 18,
    fontWeight: '500',
  },
  main: {
    maxWidth: 1200,
    marginHorizontal: 'auto',
    paddingVertical: 40,
    paddingHorizontal: width <= 768 ? 10 : 20,
  },
  howTo: {
    backgroundColor: 'rgba(27, 38, 59, 0.9)',
    padding: width <= 768 ? 20 : 25,
    borderRadius: 12,
    marginBottom: 40,
    shadowColor: '#ff6200',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 3,
  },
  howToTitle: {
    fontSize: width <= 480 ? 26 : width <= 768 ? 28 : 32,
    fontWeight: '700',
    color: '#ff6200',
    textAlign: 'center',
    marginBottom: 20,
    textShadowColor: 'rgba(255, 98, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  howToListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: width <= 768 ? 12 : 15,
    paddingLeft: width <= 768 ? 40 : 45,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 98, 0, 0.1)',
  },
  howToListNumber: {
    position: 'absolute',
    left: 0,
    width: width <= 480 ? 22 : width <= 768 ? 25 : 28,
    height: width <= 480 ? 22 : width <= 768 ? 25 : 28,
    backgroundColor: '#ff6200',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(255, 98, 0, 0.3)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 2,
  },
  howToListNumberText: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: width <= 480 ? 12 : width <= 768 ? 13 : 14,
  },
  howToListText: {
    fontSize: width <= 480 ? 14 : width <= 768 ? 15 : 16,
    lineHeight: 24,
    color: '#dcdcdc',
    flex: 1,
  },
  hero: {
    alignItems: 'center',
    paddingVertical: width <= 768 ? 30 : 50,
    backgroundColor: 'transparent', // Gradient handled by LinearGradient
  },
  heroTitle: {
    fontSize: width <= 480 ? 28 : width <= 768 ? 32 : 40,
    fontWeight: '700',
    color: '#ff6200',
    marginBottom: 15,
    textShadowColor: 'rgba(255, 98, 0, 0.4)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 10,
  },
  heroSubtitle: {
    fontSize: width <= 480 ? 16 : width <= 768 ? 18 : 20,
    color: '#dcdcdc',
    textAlign: 'center',
    maxWidth: width <= 768 ? '90%' : 600,
  },
  content: {
    paddingVertical: 20,
  },
  contentHeading: {
    fontSize: width <= 480 ? 22 : width <= 768 ? 24 : 28,
    fontWeight: '600',
    color: '#ff6200',
    marginVertical: 35,
    textAlign: 'center',
    textShadowColor: 'rgba(255, 98, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    position: 'relative',
  },
  contentText: {
    fontSize: width <= 480 ? 14 : width <= 768 ? 15 : 16,
    lineHeight: 26,
    color: '#dcdcdc',
    marginBottom: 20,
    textAlign: 'justify',
  },
  highlight: {
    color: '#ff6200',
    fontWeight: '500',
    backgroundColor: 'rgba(255, 98, 0, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  footer: {
    paddingVertical: 25,
    alignItems: 'center',
    backgroundColor: 'rgba(13, 27, 42, 0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 98, 0, 0.2)',
  },
  footerText: {
    fontSize: width <= 480 ? 14 : 15,
    color: '#dcdcdc',
  },
});