import { StyleSheet, Dimensions } from 'react-native';

const { height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#222',
    borderBottomWidth: 2,
    borderBottomColor: '#ff6200',
  },
  navbarBrand: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 40,
    height: 40,
  },
  logoText: {
    color: '#ff6200',
    fontSize: 22,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  menuToggle: {
    padding: 10,
  },
  navLinks: {
    position: 'absolute',
    top: 70,
    right: 15,
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 12,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  navLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  navLinkActive: {
    backgroundColor: '#ff6200',
    borderRadius: 5,
  },
  navIcon: {
    marginRight: 12,
  },
  navLinkText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  connectButtonContainer: {
    alignItems: 'center',
    marginVertical: 15,
  },
  leaderboardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#ff6200',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginVertical: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  iconPulse: {
    marginRight: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  content: {
    flexGrow: 1,
    padding: 20,
  },
  card: {
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ff620033',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  cardBody: {
    flex: 1,
  },
  cardTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 15,
    borderWidth: 2,
    borderColor: '#ff6200',
  },
  cardTitle: {
    color: '#ff6200',
    fontSize: 24,
    fontWeight: 'bold',
  },
  statText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 8,
  },
  progressBar: {
    height: 22,
    backgroundColor: '#333',
    borderRadius: 11,
    overflow: 'hidden',
    marginVertical: 12,
    position: 'relative',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#ff6200',
  },
  progressText: {
    position: 'absolute',
    color: '#fff',
    fontSize: 12,
    textAlign: 'center',
    width: '100%',
    lineHeight: 22,
  },
  infoText: {
    color: '#ddd',
    fontSize: 14,
    marginVertical: 8,
  },
  eventText: {
    color: '#ff6200',
    fontSize: 14,
    fontStyle: 'italic',
    marginVertical: 8,
  },
  gameMessage: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginVertical: 12,
    fontWeight: '500',
  },
  sectionTitle: {
    color: '#ff6200',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 10,
  },
  inventoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  inventoryItemText: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  itemImage: {
    width: 32,
    height: 32,
    marginRight: 12,
  },
  inventoryText: {
    color: '#fff',
    fontSize: 16,
  },
  rareItem: {
    color: '#ff6200',
    fontWeight: 'bold',
  },
  inventoryList: {
    height: screenHeight * 0.25, // Dynamic height based on screen size
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 12,
  },
  actionButton: {
    backgroundColor: '#ff6200',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
    flex: 1,
    marginHorizontal: 6,
    alignItems: 'center',
  },
  smallButton: {
    backgroundColor: '#ff6200',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  actionButtonContainer: {
    marginTop: 20,
  },
  disabledButton: {
    backgroundColor: '#888',
    opacity: 0.6,
  },
  modal: {
    justifyContent: 'center',
    margin: 20,
  },
  modalContent: {
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 20,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: '#ff620033',
  },
  modalTitle: {
    color: '#ff6200',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 5,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 6,
    backgroundColor: '#333',
  },
  activeTab: {
    backgroundColor: '#ff6200',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  tabText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  ingredientItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  ingredientText: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  ingredientCount: {
    color: '#ff6200',
    fontSize: 16,
    fontWeight: 'bold',
  },
  ingredientList: {
    height: screenHeight * 0.3,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  modalButton: {
    backgroundColor: '#ff6200',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  npcItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  npcText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  npcDialogue: {
    color: '#ddd',
    fontSize: 14,
    marginTop: 5,
  },
  npcList: {
    height: screenHeight * 0.3,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  enemyImage: {
    width: 100,
    height: 100,
    marginVertical: 10,
  },
  combatText: {
    color: '#fff',
    fontSize: 16,
    marginVertical: 5,
    textAlign: 'center',
  },
  logText: {
    color: '#ccc',
    fontSize: 14,
    marginVertical: 2,
  },
  combatLog: {
    height: screenHeight * 0.2,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 10,
  },
  combatResult: {
    color: '#ff6200',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 15,
  },
  skillList: {
    height: screenHeight * 0.2,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  recipeList: {
    height: screenHeight * 0.2,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  marketItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  marketText: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  marketList: {
    height: screenHeight * 0.25,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  leaderboardItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  leaderboardText: {
    color: '#fff',
    fontSize: 16,
  },
  leaderboardList: {
    height: screenHeight * 0.4,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  questItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  questText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  questReward: {
    color: '#ddd',
    fontSize: 14,
    marginTop: 5,
  },
  questList: {
    height: screenHeight * 0.3,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  taskItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  taskText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  taskReward: {
    color: '#ddd',
    fontSize: 14,
    marginTop: 5,
  },
  taskList: {
    height: screenHeight * 0.3,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  skillTree: {
    marginBottom: 15,
  },
  skillItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  skillText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  skillEffect: {
    color: '#ddd',
    fontSize: 14,
    marginTop: 5,
  },
  skillTreeList: {
    height: screenHeight * 0.4,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  guildItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  guildText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  guildList: {
    height: screenHeight * 0.3,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  townItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  townText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  townList: {
    height: screenHeight * 0.3,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  input: {
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 8,
    padding: 12,
    marginVertical: 12,
    fontSize: 16,
  },
  picker: {
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 8,
    marginVertical: 12,
  },
  travelText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginVertical: 15,
  },
  guideText: {
    color: '#ddd',
    fontSize: 14,
    marginVertical: 8,
  },
  bold: {
    fontWeight: 'bold',
    color: '#ff6200',
  },
});