import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A2E',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A1A2E',
  },
  loadingText: {
    color: '#FFFFFF',
    fontSize: 16,
    marginTop: 10,
    fontFamily: 'Roboto-Regular',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A1A2E',
    padding: 20,
  },
  errorTitle: {
    color: '#FF5252',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  input: {
    backgroundColor: '#2C2C44',
    color: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    fontSize: 16,
    width: '100%',
    fontFamily: 'Roboto-Regular',
  },
  actionButton: {
    backgroundColor: '#F36316',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },
  secondaryButton: {
    backgroundColor: '#2C2C44',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
  },
  buttonIcon: {
    marginRight: 8,
  },
  balanceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    backgroundColor: '#2C2C44',
    borderRadius: 8,
    margin: 10,
  },
  balanceItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  balanceIcon: {
    marginRight: 5,
  },
  balanceText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#2C2C44',
    borderBottomWidth: 1,
    borderBottomColor: '#F36316',
  },
  headerButton: {
    padding: 10,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  messageContainer: {
    padding: 10,
    margin: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  successMessage: {
    backgroundColor: '#28A745',
  },
  errorMessage: {
    backgroundColor: '#FF5252',
  },
  messageText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },
  lockedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  lockIcon: {
    marginBottom: 20,
  },
  lockedMessage: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  lockedSubMessage: {
    color: '#CCCCCC',
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  paymentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  paymentButton: {
    backgroundColor: '#F36316',
    padding: 15,
    borderRadius: 8,
    margin: 5,
    width: 150,
    alignItems: 'center',
  },
  disabledButton: {
    backgroundColor: '#555',
    opacity: 0.6,
  },
  paymentButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginVertical: 5,
    fontFamily: 'Roboto-Bold',
  },
  paymentPrice: {
    color: '#CCCCCC',
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
  },
  contentContainer: {
    flex: 1,
  },
  pageContainer: {
    alignItems: 'center',
    marginVertical: 10,
  },
  pageImage: {
    width: '100%',
    height: 600,
    borderRadius: 8,
  },
  readingOptions: {
    padding: 10,
    alignItems: 'center',
  },
  smpButton: {
    backgroundColor: '#F36316',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  smpButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },
  readingModeText: {
    color: '#CCCCCC',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },
  navigation: {
    padding: 10,
    backgroundColor: '#2C2C44',
    borderTopWidth: 1,
    borderTopColor: '#F36316',
  },
  navRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  navButton: {
    flex: 1,
    backgroundColor: '#F36316',
    padding: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  navButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },
  navPlaceholder: {
    flex: 1,
    marginHorizontal: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#2C2C44',
    padding: 20,
    borderRadius: 12,
    width: '90%',
    maxWidth: 400,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 10, // Increased padding for larger touch area
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  modalSubtitle: {
    color: '#CCCCCC',
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  transactionDetails: {
    marginBottom: 20,
  },
  detailText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginVertical: 5,
    fontFamily: 'Roboto-Regular',
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  modalConfirmButton: {
    backgroundColor: '#F36316',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginRight: 5,
    alignItems: 'center',
    minHeight: 48, // Ensure sufficient touch area
  },
  modalCancelButton: {
    backgroundColor: '#555',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginLeft: 5,
    alignItems: 'center',
    minHeight: 48, // Ensure sufficient touch area
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },
  modalNote: {
    color: '#CCCCCC',
    fontSize: 12,
    marginTop: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  passwordModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardAvoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  passwordModalContent: {
    backgroundColor: '#2C2C44',
    padding: 20,
    borderRadius: 12,
    width: '90%',
    maxWidth: 400,
  },
  passwordModalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: 'Roboto-Bold',
  },
  passwordInput: {
    backgroundColor: '#1A1A2E',
    color: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
  },
  inputError: {
    borderColor: '#FF5252',
    borderWidth: 1,
  },
  passwordErrorText: {
    color: '#FF5252',
    fontSize: 14,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  passwordModalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  passwordModalConfirmButton: {
    backgroundColor: '#F36316',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginRight: 5,
    alignItems: 'center',
    minHeight: 48, // Ensure sufficient touch area
  },
  passwordModalCancelButton: {
    backgroundColor: '#555',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginLeft: 5,
    alignItems: 'center',
    minHeight: 48, // Ensure sufficient touch area
  },
  passwordModalButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Bold',
  },
});