// ./styles/NovelPageStyles.js
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#0F0F1F',
  },
  contentContainer: {
    paddingBottom: 32,
    paddingHorizontal: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0F0F1F',
  },
  loadingText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Poppins-Regular',
    marginTop: 12,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0F0F1F',
  },
  errorText: {
    color: '#ff5555',
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 24,
  },
  backHomeLink: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D94F04',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    shadowColor: '#D94F04',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
  },
  backHomeText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 8,
  },
  navbar: {
    backgroundColor: '#1A1A2E',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#D94F04',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  navContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#D94F04',
  },
  logoText: {
    color: '#fff',
    fontSize: 22,
    fontFamily: 'Poppins-Bold',
    marginLeft: 10,
  },
  menuToggle: {
    padding: 10,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    zIndex: 10,
  },
  navItems: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: width * 0.7,
    backgroundColor: '#1A1A2E',
    padding: 24,
    zIndex: 20,
    borderLeftWidth: 1,
    borderLeftColor: '#D94F04',
  },
  navItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: 12,
  },
  navItemText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Poppins-Medium',
    marginLeft: 12,
  },
  connectBtn: {
    marginTop: 24,
    alignSelf: 'center',
    width: '100%',
  },
  novelContainer: {
    paddingHorizontal: 0, // Handled by FlatList contentContainerStyle
  },
  novelHeaderGradient: {
    borderRadius: 16,
    marginVertical: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  novelHeader: {
    alignItems: 'center',
  },
  novelTitle: {
    color: '#fff',
    fontSize: 28,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  novelImageWrapper: {
    position: 'relative',
    marginBottom: 16,
  },
  novelImage: {
    width: width * 0.55,
    height: width * 0.8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D94F04',
  },
  imageGlow: {
    position: 'absolute',
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    backgroundColor: 'rgba(217, 79, 4, 0.15)',
    borderRadius: 16,
    zIndex: -1,
  },
  novelViews: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(217, 79, 4, 0.2)',
  },
  novelViewsText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    marginLeft: 8,
  },
  novelIntro: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    lineHeight: 26,
  },
  highlight: {
    color: '#D94F04',
    fontFamily: 'Poppins-Bold',
  },
  chaptersSection: {
    marginBottom: 16,
  },
  commentsSection: {
    marginVertical: 16,
  },
  commentsToggle: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  sectionTitle: {
    color: '#D94F04',
    fontSize: 24,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  chapterCard: {
    flex: 1,
    margin: 8,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  chapterContent: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  chapterGradient: {
    padding: 16,
    alignItems: 'center',
  },
  chapterTitle: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
  },
  chapterAccent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#D94F04',
  },
  noChapters: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginVertical: 24,
  },
  connectPopupOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
  },
  connectPopup: {
    width: '90%',
    maxWidth: 400,
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  closePopupButton: {
    position: 'absolute',
    top: 16,
    right: 16,
  },
  popupTitle: {
    color: '#fff',
    fontSize: 24,
    fontFamily: 'Poppins-Bold',
    marginBottom: 16,
  },
  popupMessage: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginBottom: 24,
  },
  connectWalletButton: {
    marginBottom: 24,
    width: '100%',
    alignItems: 'center',
  },
  errorMessage: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ff5555',
    padding: 12,
    borderRadius: 10,
    marginVertical: 8,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  errorMessageText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    flex: 1,
  },
  clearErrorButton: {
    padding: 8,
  },
  footer: {
    padding: 16,
    alignItems: 'center',
    backgroundColor: '#1A1A2E',
    borderTopWidth: 1,
    borderTopColor: '#D94F04',
  },
  footerText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
  },
});