// ../styles/StatStyles.js
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A2E',
    // Gradient background (fallback for now, can use react-native-linear-gradient in component)
    // background: 'linear-gradient(135deg, #1A1A2E 0%, #23234A 100%)',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: 'rgba(42,42,62,0.95)',
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A4E',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  headerButton: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(242,140,56,0.08)',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 1,
    fontFamily: 'System', // Use a modern font if available
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#FFFFFF',
  },
  errorContainer: {
    backgroundColor: '#EF5350',
    padding: 10,
    marginHorizontal: 20,
    borderRadius: 12,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  errorText: {
    color: '#FFFFFF',
    fontSize: 14,
    textAlign: 'center',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100, // Ensure footer is visible
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: 1.2,
    fontFamily: 'System',
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  statCard: {
    width: '48%',
    backgroundColor: 'rgba(42,42,62,0.85)',
    borderRadius: 18,
    padding: 18,
    marginBottom: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(242,140,56,0.13)',
    // Glassmorphism effect (for iOS, use BlurView in component for best effect)
    // backdropFilter: 'blur(8px)',
  },
  statTitle: {
    fontSize: 16,
    color: '#F28C38',
    marginBottom: 5,
    textAlign: 'center',
    fontWeight: '600',
    letterSpacing: 0.5,
    fontFamily: 'System',
  },
  statValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 2,
    letterSpacing: 1.1,
    fontFamily: 'System',
    textShadowColor: 'rgba(242,140,56,0.18)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  chartGrid: {
    marginTop: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(242,140,56,0.13)',
    paddingTop: 18,
  },
  chartCard: {
    backgroundColor: 'rgba(42,42,62,0.85)',
    borderRadius: 18,
    padding: 18,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(242,140,56,0.13)',
    // Glassmorphism effect (for iOS, use BlurView in component for best effect)
    // backdropFilter: 'blur(8px)',
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F28C38',
    marginBottom: 10,
    textAlign: 'center',
    letterSpacing: 0.7,
    fontFamily: 'System',
  },
  chart: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 2,
  },
  footer: {
    padding: 15,
    backgroundColor: 'rgba(42,42,62,0.95)',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#3A3A4E',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
  },
  footerText: {
    fontSize: 12,
    color: '#FFFFFF',
    letterSpacing: 0.5,
    fontFamily: 'System',
  },
});