name: Build and Release APK
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Set up EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}
      - name: Build APK
        id: eas_build
        run: |
          eas build --platform android --profile dapp-store --non-interactive --json > build-output.json
          echo "build_url=$(jq -r '.builds[0].artifacts.buildUrl' build-output.json)" >> $GITHUB_OUTPUT
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
      - name: Download APK
        run: |
          mkdir -p dapp-store-build
          curl -L -o dapp-store-build/sempaihq-unsigned.apk "${{ steps.eas_build.outputs.build_url }}"
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 -d > ./dapp-store-signing-keys/release-key.keystore
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install Android Build Tools
        run: |
          sdkmanager --install "build-tools;35.0.0"
        env:
          ANDROID_HOME: $HOME/android-sdk
        shell: bash
      - name: Sign APK
        run: |
          ~/android-sdk/build-tools/35.0.0/apksigner sign \
            --ks ./dapp-store-signing-keys/release-key.keystore \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias 41349a67d6d871c3e72ec878e54978cc \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out ./dapp-store-build/sempaihq-signed.apk \
            ./dapp-store-build/sempaihq-unsigned.apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dapp-store-build/sempaihq-signed.apk
          asset_name: sempaihq-${{ github.ref_name }}-signed.apk
          asset_content_type: application/vnd.android.package-archive